services:
  backend:
    build:
      context: ../backend
    env_file:
      - ../backend/.env
    ports:
      - 8080:8080
    environment:
      - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    logging:
      driver: json-file
    networks:
      - observability

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    networks:
      - observability

networks:
  observability:
    driver: bridge
