input {
beats {
port => 5044
}
}

filter {
if [container] {
json {
source => "message"
target => "json"
skip_on_invalid_json => true
}
}
}

output {
elasticsearch {
hosts => ["http://elasticsearch:9200"]
index => "upblit-logs-%{+YYYY.MM.dd}"
}
}
